### ISSUE TITLE
PS Down loader issue

### ISSUE THREAD

**Issue by wgx731** [yemyat/PythonLeo#2]
I have encountered list out of bounds error, it seems that when there is zip file inside the problem statement folder, I will encounter this error. Or is it my version is old one? :-) THX

**Comment by yemyat** [comment]
I've never encountered this problem until now. Neither my friends did. First of all, thanks for reporting the issue. 

I'll look into that over the weekends and probably ask Will (contributor of this extractor) to improve his work. In the meantime, I will also try to put more error checking and condition for the PS downloader such as ability to check if today's problem was indeed a problem and not assignment as some users are having problems with that. So, wait for the push over the weekends. :)
